"""Evidence extraction pipeline; notes are generated by a separate consumer."""

from __future__ import annotations

import hashlib
import math
import os

from . import evidence
from .acquisition import fill_segment_ends
from .config import DEFAULT_STT_MODEL, OCR_RELIABLE_CONFIDENCE_THRESHOLD
from .resources import ResourceSampler
from .source import InputSource, SourceKind, classify_source
from .synthesis import render_transcript_md, write_text


def _positive_finite_duration(*values: object) -> float:
    for value in values:
        try:
            duration = float(value)
        except (TypeError, ValueError):
            continue
        if math.isfinite(duration) and duration > 0:
            return duration
    return 0.0


def _sha256_file(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _source_id(source: InputSource) -> str:
    if source.kind is SourceKind.YOUTUBE:
        return f"youtube:{source.video_id}"
    return f"sha256:{_sha256_file(source.locator)}"


def _directory_bytes(root: str) -> int:
    total = 0
    for current, _dirs, files in os.walk(root):
        for filename in files:
            path = os.path.join(current, filename)
            try:
                total += os.path.getsize(path)
            except OSError:
                continue
    return total


def _safe_reliable(frame, ocr_status: str) -> bool | None:
    if ocr_status in {"skipped", "failed"} or not (frame.ocr_text or "").strip():
        return None
    confidence = frame.ocr_confidence
    return None if confidence is None else bool(confidence >= OCR_RELIABLE_CONFIDENCE_THRESHOLD)


def _frame_items(frames: list, out_dir: str, ocr_status: str) -> tuple[list[dict], dict[str, str]]:
    ordered = sorted(frames, key=lambda item: float(item.timestamp))
    items: list[dict] = []
    ids_by_path: dict[str, str] = {}
    for index, frame in enumerate(ordered, start=1):
        path = os.path.abspath(frame.image_path)
        evidence.assert_contained(out_dir, path)
        if not os.path.isfile(path):
            raise evidence.ContractError("ARTIFACT_INCOMPLETE", "A retained evidence frame is missing.")
        if ocr_status == "skipped":
            annotation_status = "skipped"
        elif ocr_status == "failed":
            annotation_status = "failed"
        else:
            annotation_status = "text" if (frame.ocr_text or "").strip() else "no-text"
        frame_id = f"f{index:04d}"
        ids_by_path[os.path.normcase(path)] = frame_id
        items.append({
            "id": frame_id,
            "start": round(float(frame.timestamp), 3),
            "path": path,
            "sha256": _sha256_file(path),
            "width": frame.meta.get("width"),
            "height": frame.meta.get("height"),
            "ocr": {
                "status": annotation_status,
                "text": (frame.ocr_text or "") or None,
                "is_slide": bool(frame.is_slide),
                "reliable": _safe_reliable(frame, ocr_status),
            },
        })
    return items, ids_by_path


def _extract_source(
    source_argument: str,
    output_dir: str,
    force_stt: bool = False,
    model: str = DEFAULT_STT_MODEL,
    *,
    keep_frames: bool = False,
    skip_ocr: bool = False,
    source: InputSource | None = None,
    metadata=None,
    resources: ResourceSampler,
) -> dict:
    """Extract speech and visual evidence into ``output_dir`` and write v2 JSON.

    The directory is expected to be new or pre-created by the caller. This
    function never writes notes, synthesis handoff, or notes coverage files.
    """
    from . import acquisition, media, visual
    from .coverage import gap_check, scene_coverage
    from .vad import detect_speech_spans

    source = source or classify_source(source_argument)
    metadata = metadata or media.probe_source(source)
    out_dir = os.path.realpath(os.path.abspath(output_dir))
    os.makedirs(out_dir, exist_ok=True)
    source_resolution = {"width": None, "height": None}
    raw_frames = []
    representative_frames = []
    slide_frames = []
    ocr_engine = "not_applicable"
    ocr_status = "skipped"
    ocr_failed = False

    with resources.stage("speech"):
        track = acquisition.acquire_speech(source, out_dir, force_stt=force_stt, model=model)
        duration = _positive_finite_duration(metadata.duration, track.meta.get("duration"))
        speech_spans = (
            detect_speech_spans(track.meta.get("audio_path", os.path.join(out_dir, "audio.wav")), duration)
            if os.path.isfile(track.meta.get("audio_path", os.path.join(out_dir, "audio.wav")))
            else [(0.0, duration)]
        )
        segments = fill_segment_ends(sorted(track.segments, key=lambda segment: segment.t), duration)

    frames_dir = os.path.join(out_dir, "frames")
    if source.has_video:
        os.makedirs(frames_dir, exist_ok=True)
        with resources.stage("frames"):
            video_path = media.resolve_video(source, out_dir)
            if video_path is None:
                raise RuntimeError("Video source did not resolve to a video path")
            source_resolution = dict(zip(("width", "height"), media.probe_video_resolution(video_path)))
            raw_frames = visual.extract_candidate_frames(video_path, frames_dir)
        with resources.stage("dedupe"):
            representative_frames = sorted(visual.dedupe_frames(raw_frames), key=lambda frame: float(frame.timestamp))
        with resources.stage("ocr"):
            if skip_ocr:
                for frame in representative_frames:
                    frame.ocr_text = ""
                    frame.is_slide = True
                slide_frames = list(representative_frames)
                ocr_engine = "skipped"
                ocr_status = "skipped"
            else:
                from .ocr import ocr_frames

                try:
                    slide_frames, ocr_engine = ocr_frames(representative_frames)
                    ocr_status = "completed-with-text" if any(
                        (frame.ocr_text or "").strip() for frame in representative_frames
                    ) else "completed-no-text"
                except Exception:  # noqa: BLE001 - OCR failure is a bounded evidence state.
                    slide_frames = []
                    ocr_engine = "failed"
                    ocr_status = "failed"
                    ocr_failed = True
            visual.cleanup_raw_frames(raw_frames, representative_frames, keep_frames=keep_frames)
            frame_items, frame_ids = _frame_items(representative_frames, out_dir, ocr_status)
    else:
        frame_items, frame_ids = [], {}
        if source.kind is not SourceKind.LOCAL_AUDIO:
            raise ValueError(f"Unsupported source kind: {source.kind!r}")

    title = metadata.title or track.meta.get("title") or metadata.video_id or source.video_id or source.title_hint or "video"
    source_data = source.safe_as_dict()
    source_data.update({
        "id": _source_id(source),
        "title": title,
        "duration_sec": round(duration, 3),
        "resolution": source_resolution,
    })
    if source.kind is SourceKind.YOUTUBE:
        source_data["citation"] = {"kind": "youtube", "video_id": source.video_id}
    segment_items = [
        {"id": f"s{index:04d}", "start": round(float(segment.t), 3),
         "end": round(float(segment.end), 3), "text": segment.text}
        for index, segment in enumerate(segments, start=1)
    ]
    transcript_segments = [{"t": segment.t, "text": segment.text} for segment in segments]
    speech_source = track.source
    transcript_md = render_transcript_md({"title": title, "speech_source": speech_source}, transcript_segments)
    transcript_path = os.path.join(out_dir, "transcript.md")
    write_text(transcript_md, transcript_path)

    raw_sample_times = [round(float(frame.timestamp), 3) for frame in raw_frames]
    visual_required = source.has_video
    ocr_required = visual_required and not skip_ocr
    note_frame_ids = [frame_ids[os.path.normcase(os.path.abspath(frame.image_path))] for frame in slide_frames]
    gap = gap_check(speech_spans, [float(segment.t) for segment in segments], duration)
    scene = scene_coverage(
        raw_sample_times, speech_spans, duration,
        slide_frames_total=len(slide_frames),
        slide_frames_with_text=sum(bool((frame.ocr_text or "").strip()) for frame in slide_frames),
        visual_required=visual_required,
        ocr_required=ocr_required,
        ocr_failed=ocr_failed,
    )
    transcript_present = bool(transcript_md.strip() and os.path.isfile(transcript_path) and os.path.getsize(transcript_path) > 0)
    frames_present = not visual_required or bool(frame_items and all(os.path.isfile(item["path"]) for item in frame_items))
    reasons: list[dict] = []
    if not gap["pass"]:
        reasons.append(evidence.reason("SPEECH_INCOMPLETE"))
    if visual_required and not scene["timeline_pass"]:
        reasons.append(evidence.reason("VISUAL_INCOMPLETE"))
    if ocr_required and ocr_failed:
        reasons.append(evidence.reason("OCR_FAILED"))
    elif ocr_required and not scene["slide_text_pass"]:
        reasons.append(evidence.reason("OCR_INCOMPLETE"))
    if not transcript_present or not frames_present:
        reasons.append(evidence.reason("ARTIFACT_INCOMPLETE"))

    hard_failure = ocr_failed or not transcript_present or not frames_present
    timestamp = evidence.timestamp_integrity(
        duration, segment_items, frame_items, allow_unknown_duration=not source.has_video,
    )
    if not timestamp["pass"]:
        reasons.append(evidence.reason("TIMESTAMP_INVALID"))
        hard_failure = True
    if hard_failure:
        extraction_status = "fail"
        if ocr_failed:
            failure_info = evidence.failure("OCR_FAILED")
        elif not timestamp["pass"]:
            failure_info = evidence.failure("TIMESTAMP_INVALID")
        else:
            failure_info = evidence.failure("ARTIFACT_INCOMPLETE")
    else:
        extraction_status = "warn" if reasons else "pass"
        failure_info = None

    fallback_code = track.meta.get("fallback_code")
    if fallback_code is None and speech_source == "stt" and source.kind is not SourceKind.YOUTUBE:
        fallback_code = "local_source"
    allowed_fallbacks = {"captions_unavailable", "captions_unusable", "forced_stt", "local_source"}
    fallback = {"code": fallback_code} if fallback_code in allowed_fallbacks else None
    speech = {
        "source": speech_source,
        "language": track.language,
        "model": track.meta.get("model", model) if speech_source == "stt" else None,
        "fallback": fallback,
    }
    resources_data = resources.finish(
        artifact_bytes=_directory_bytes(out_dir),
        frames_candidate=len(raw_frames),
        frames_retained=len(frame_items),
    )
    manifest = evidence.build_evidence_manifest(
        source=source_data,
        output_dir=out_dir,
        paths={
            "evidence": os.path.join(out_dir, "evidence.json"),
            "transcript": transcript_path,
            "frames_dir": frames_dir if visual_required else None,
            "output_dir": out_dir,
        },
        transcript_segments=segment_items,
        frames=frame_items,
        speech=speech,
        speech_completeness={
            "status": "pass" if gap["pass"] else "fail",
            **gap,
            "speech_spans": [[round(float(start), 3), round(float(end), 3)] for start, end in speech_spans],
        },
        visual_completeness={
            **scene,
            "status": "not-applicable" if not visual_required else ("pass" if scene["timeline_pass"] else "fail"),
            "pass": not visual_required or scene["timeline_pass"],
            "raw_sample_times": raw_sample_times,
            "notes_frame_ids": note_frame_ids,
        },
        timestamp_integrity_result=timestamp,
        ocr_status=ocr_status,
        ocr_engine=ocr_engine,
        extraction_status=extraction_status,
        reasons=reasons,
        resources=resources_data,
        failure_info=failure_info,
    )
    evidence.write_json(manifest, os.path.join(out_dir, "evidence.json"))
    return {"output_dir": out_dir, "manifest": manifest}
def extract_source(
    source_argument: str,
    output_dir: str,
    force_stt: bool = False,
    model: str = DEFAULT_STT_MODEL,
    *,
    keep_frames: bool = False,
    skip_ocr: bool = False,
    source: InputSource | None = None,
    metadata=None,
) -> dict:
    """Extract speech and visual evidence into a directory and write v2 JSON."""
    resources = ResourceSampler().start()
    try:
        return _extract_source(
            source_argument,
            output_dir,
            force_stt,
            model,
            keep_frames=keep_frames,
            skip_ocr=skip_ocr,
            source=source,
            metadata=metadata,
            resources=resources,
        )
    except BaseException:
        resources.abort()
        raise




__all__ = ["extract_source"]
